#######################################################################
# File name : docker-compose.yml
# Author : Olivier Galand (31/12/2021)
# Author email : galand.olivier.david@gmail.com
# Project : CashFactory
# Project repository : https://github.com/OlivierGaland/CashFactory
# 
# Docker-compose file of CashFactory
#######################################################################
version: '3.5'

services:
    #Start of Portainer + Webserver section :
    # Web GUI with quicklinks to apps dashboards and help : connect to your device port 80 (Webserver)
    # Container management and monitoring : connect to your device port 9000 (Portainer)
    Webserver:
        image: fnichol/uhttpd
        volumes:
            - ./www:/www
        ports:
            - 80:80
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.10
    Portainer:
        image: portainer/portainer-ce:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - 8000:8000
            - 9000:9000
            - 9443:9443
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.11
    #End of Portainer + Webserver section

    #Start of TraffMonetizer section (remove this if TraffMonetizer not wanted)
    # variables to define in .env file :
    # TRAFFMONETIZER_TOKEN : Your application token (available in TraffMonetizer dashboard)
    TraffMonetizer:
        depends_on:
            - Portainer
            - Webserver
        image: traffmonetizer/cli:latest
        restart: always
        command: start accept --token ${TRAFFMONETIZER_TOKEN}
        networks:
            default:
                ipv4_address: 172.106.0.80
    #End of Packetstream section   
    
    #Start of Repocket section (remove this if Repocket not wanted)
    # variables to define in .env file :
    # RP_EMAIL : Your application mail 
    # RP_API_KEY : Your application api key (available in repocket dashboard)
    Repocket:
        depends_on:
            - Portainer
            - Webserver
        image: repocket/repocket:latest
        restart: always
        environment:
          - RP_EMAIL
          - RP_API_KEY
        networks:
            default:
                ipv4_address: 172.106.0.90
    #End of Repocket section    


volumes:
    portainer_data:
    earnapp-data:

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
